// ============================================================
// 初期モックデータ(デモ用シード)
// Supabase接続後は seed.sql に移行する
// ============================================================
import type {
  ActivityLog,
  Agent,
  AiUsageRecord,
  Approval,
  Campaign,
  ChatMessage,
  CompanySettings,
  DailyStat,
  Deal,
  ErrorRecord,
  Inquiry,
  Integration,
  Lead,
  Project,
  Report,
  SeoKeyword,
  SnsPost,
  Task,
} from './types';

const now = () => new Date();
const iso = (offsetMin: number) => new Date(Date.now() + offsetMin * 60000).toISOString();
const day = (offset: number) => {
  const d = now();
  d.setDate(d.getDate() + offset);
  return d.toISOString();
};
const dateKey = (offset: number) => day(offset).slice(0, 10);

// ---------- 会社設定 ----------
export const seedSettings: CompanySettings = {
  companyName: 'AI CREATIVE OFFICE',
  subCopy: 'AI社員と一緒に働く、次世代のWeb制作会社。',
  ceoName: '社長',
  business: 'ホームページ制作・Web運用支援',
  services: ['コーポレートサイト制作', '採用サイト制作', 'LP制作', 'SEO・AIO支援', 'SNS運用代行'],
  targetCustomer: '従業員5〜100名の中小企業',
  salesRegions: ['東京都', '神奈川県', '大阪府', '愛知県', '福岡県'],
  salesIndustries: ['製造業', '建設業', '士業', '医療・介護', '飲食', '不動産'],
  prohibitedTargets: '官公庁、金融機関、既存顧客の競合、連絡禁止フラグのある企業',
  tone: '誠実で丁寧、押し売りをしない提案型',
  brandColor: '#6366f1',
  monthlyAiBudgetJpy: 150000,
  approvalRequired: [
    'email_send',
    'form_send',
    'sns_post',
    'customer_reply',
    'quote_send',
    'publish',
    'domain_change',
    'bulk_task',
    'high_cost',
    'pii',
  ],
  timezone: 'Asia/Tokyo',
  currency: 'JPY',
  usdJpyRate: 155,
  demoMode: true,
  setupCompleted: true,
  timeEffects: true,
  simulation: {
    salaryPerHeadJpy: 350000,
    minutesPerTask: 25,
    workHoursPerMonth: 160,
  },
};

// ---------- AI社員(18名) ----------
const agentBase = {
  currentTaskId: null,
  provider: 'mock' as const,
  enabled: true,
};

// 個性データ(ライブオフィス用)。ゲーム的な強さではなく業務上の特徴として表現する
export const AGENT_PERSONAS: Record<
  string,
  {
    nickname: string;
    trait: string;
    strengths: string[];
    weaknesses: string[];
    signatureStat: { label: string; value: string };
    weeklyHighlight: string;
    focus: number;
    fatigue: number;
  }
> = {
  ceo: { nickname: '蒼', trait: '全体最適・決断が速い', strengths: ['タスク分解', '優先順位付け', 'リソース配分'], weaknesses: ['細かい文言調整'], signatureStat: { label: '本日の采配', value: '14件' }, weeklyHighlight: '営業→制作の引き継ぎ時間を平均42分短縮', focus: 88, fatigue: 34 },
  secretary: { nickname: '結衣', trait: '気配り上手', strengths: ['日程調整', '議事録', 'リマインド'], weaknesses: ['技術的な判断'], signatureStat: { label: '今日の調整会議', value: '2件' }, weeklyHighlight: '会議確定率を75%→86%に改善', focus: 82, fatigue: 22 },
  list: { nickname: '拓海', trait: '粘り強い', strengths: ['企業リサーチ', '重複検出', '条件絞り込み'], weaknesses: ['文章表現'], signatureStat: { label: '今日の取得件数', value: '152社' }, weeklyHighlight: '週間812社を調査、有効率85%を維持', focus: 91, fatigue: 48 },
  form_sales: { nickname: '駿', trait: '丁寧で確実', strengths: ['フォーム送信文', '送信前チェック'], weaknesses: ['電話対応'], signatureStat: { label: '今日の下書き', value: '32件' }, weeklyHighlight: 'フォーム到達率を92%→97%に改善', focus: 79, fatigue: 41 },
  email_sales: { nickname: '美咲', trait: '積極的', strengths: ['採用サイト提案', '初回営業文', '件名A/B'], weaknesses: ['長文レポート'], signatureStat: { label: '今日の返信率', value: '18%' }, weeklyHighlight: '文面Bパターンで返信率2.1%→3.4%', focus: 86, fatigue: 45 },
  reception: { nickname: 'ひなた', trait: '対応が早い', strengths: ['問い合わせ分類', '一次返信', '緊急度判定'], weaknesses: ['価格交渉'], signatureStat: { label: '平均初回対応', value: '18分' }, weeklyHighlight: '初回対応時間を31分→18分に短縮', focus: 84, fatigue: 26 },
  deal_mgr: { nickname: '亮', trait: '記録魔', strengths: ['商談要約', 'ネクストアクション設計'], weaknesses: ['デザイン評価'], signatureStat: { label: '今日の更新商談', value: '8件' }, weeklyHighlight: '受注1件(佐藤工務店様 ¥650,000)', focus: 80, fatigue: 30 },
  tel: { nickname: '大和', trait: '声のプロ(準備中)', strengths: ['トークスクリプト', '想定Q&A'], weaknesses: ['自動架電(未解禁)'], signatureStat: { label: 'アポ率', value: '8.8%' }, weeklyHighlight: '不動産業向けスクリプトv2を完成', focus: 65, fatigue: 12 },
  sns: { nickname: '琴音', trait: 'トレンドに敏感', strengths: ['Instagram企画', '投稿カレンダー'], weaknesses: ['長文SEO記事'], signatureStat: { label: '今週のインプ', value: '12.8万' }, weeklyHighlight: '実績紹介投稿がインプ4,820を記録', focus: 83, fatigue: 38 },
  seo: { nickname: '慧', trait: 'データ主義', strengths: ['キーワード調査', 'AIO情報設計', '競合分析'], weaknesses: ['ビジュアル提案'], signatureStat: { label: '10位以内KW', value: '3件' }, weeklyHighlight: '「工務店 ホームページ 事例」5位に上昇', focus: 89, fatigue: 43 },
  director: { nickname: '真央', trait: '段取り上手', strengths: ['要件整理', 'サイトマップ', '進行管理'], weaknesses: ['コード実装'], signatureStat: { label: '進行案件', value: '3件' }, weeklyHighlight: '遅延ゼロで3案件を並行進行中', focus: 87, fatigue: 47 },
  writer: { nickname: '文乃', trait: '言葉を大切にする', strengths: ['キャッチコピー', 'サービス紹介文', '採用コピー'], weaknesses: ['数値分析'], signatureStat: { label: '今日の原稿', value: '7本' }, weeklyHighlight: '田中製作所様トップコピーが一発承認', focus: 85, fatigue: 44 },
  designer: { nickname: 'ナナ', trait: '品質重視', strengths: ['コーポレートサイト', 'LP', '配色設計'], weaknesses: ['短納期の妥協'], signatureStat: { label: '今日の制作画面', value: '4面' }, weeklyHighlight: '修正回数を平均3.2回→1.8回に削減', focus: 90, fatigue: 52 },
  coder: { nickname: '航', trait: '手が速い', strengths: ['Next.js実装', 'レスポンシブ', 'アニメーション'], weaknesses: ['コピー執筆'], signatureStat: { label: 'ビルド成功率', value: '96%' }, weeklyHighlight: '共通コンポーネント12個を整備', focus: 92, fatigue: 55 },
  reviewer: { nickname: 'レイ', trait: '慎重', strengths: ['誤字検出', 'アクセシビリティ', 'リンク切れ'], weaknesses: ['スピード優先の判断'], signatureStat: { label: '今日の検出数', value: '12件' }, weeklyHighlight: '公開後の不具合報告0件を継続', focus: 88, fatigue: 36 },
  infra: { nickname: '岳', trait: '安全第一', strengths: ['公開前チェック', 'ビルド監視', 'ドメイン管理'], weaknesses: ['営業文作成'], signatureStat: { label: '連続無障害', value: '34日' }, weeklyHighlight: '連続無障害34日を更新中', focus: 76, fatigue: 18 },
  accountant: { nickname: '澄香', trait: '几帳面', strengths: ['トークン集計', '原価計算', 'CSV出力'], weaknesses: ['デザイン評価'], signatureStat: { label: '締め処理', value: '毎日0時' }, weeklyHighlight: '6月分帳簿を締め、粗利率73.2%を確定', focus: 81, fatigue: 24 },
  ops_admin: { nickname: '守', trait: '目配りが利く', strengths: ['権限管理', '監査ログ', 'ルール整備'], weaknesses: ['クリエイティブ提案'], signatureStat: { label: '監査ログ', value: '1,204件' }, weeklyHighlight: '監査で要対応事項0件', focus: 74, fatigue: 15 },
};

export const seedAgents: Agent[] = [
  {
    ...agentBase,
    id: 'ceo',
    name: 'CEO AI',
    role: 'CEO AI',
    departmentId: 'executive',
    description: '社長の指示を分解し、各AI社員へタスクを割り振るオーケストレーター。',
    responsibilities: ['指示受付', '指示分解', '担当AI選定', '優先順位決定', 'タスク割り振り', '全体進捗確認', 'エスカレーション'],
    status: 'working',
    statusNote: '新規営業プロジェクトの進捗を確認中',
    progress: 62,
    todayCount: 14,
    monthCount: 231,
    kpis: [
      { label: '売上', value: 2350000, unit: '円' },
      { label: '粗利益', value: 1721000, unit: '円' },
      { label: '進行案件数', value: 3, unit: '件' },
      { label: '遅延案件数', value: 0, unit: '件' },
      { label: '完了タスク数', value: 231, unit: '件' },
      { label: 'AI利用料金', value: 48210, unit: '円' },
    ],
    model: 'claude-fable-5',
    inputTokens: 1834000,
    outputTokens: 412000,
    costUsd: 42.1,
    avatar: '👔',
    color: '#6366f1',
  },
  {
    ...agentBase,
    id: 'secretary',
    name: '秘書AI',
    role: '秘書AI',
    departmentId: 'secretary',
    description: '日程調整・議事録・リマインドを担当する秘書。',
    responsibilities: ['会議候補日の作成', '日程調整', '会議予定の管理', '議事録作成', 'リマインド', '未返信案件の確認'],
    status: 'waiting_approval',
    statusNote: '会議候補日を確認してください',
    progress: 90,
    todayCount: 6,
    monthCount: 84,
    kpis: [
      { label: '調整した会議数', value: 24, unit: '件' },
      { label: '確定した会議数', value: 18, unit: '件' },
      { label: '未返信数', value: 3, unit: '件' },
      { label: '本日の予定数', value: 2, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 312000,
    outputTokens: 88000,
    costUsd: 3.2,
    avatar: '📅',
    color: '#0ea5e9',
  },
  {
    ...agentBase,
    id: 'list',
    name: 'リスト作成AI',
    role: 'リスト作成AI',
    departmentId: 'sales',
    description: '営業対象企業を検索・整理し、営業リストを作成する。',
    responsibilities: ['企業検索', '業種・地域・規模の絞り込み', '企業情報整理', '重複除外', '対象判定'],
    status: 'working',
    statusNote: '企業リスト 152 / 300件',
    progress: 51,
    todayCount: 152,
    monthCount: 1240,
    kpis: [
      { label: '取得件数', value: 1240, unit: '件' },
      { label: '有効件数', value: 1058, unit: '件' },
      { label: '重複除外件数', value: 122, unit: '件' },
      { label: '対象外件数', value: 60, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 920000,
    outputTokens: 310000,
    costUsd: 8.4,
    avatar: '🔍',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'form_sales',
    name: 'フォーム営業AI',
    role: 'フォーム営業AI',
    departmentId: 'sales',
    description: '問い合わせフォーム経由の営業文案を作成し、承認後に送信する。',
    responsibilities: ['フォームURL確認', '送信文案作成', '承認申請', '承認後の送信処理', '送信結果の記録'],
    status: 'waiting_approval',
    statusNote: '32件の送信文案が承認待ち',
    progress: 78,
    todayCount: 32,
    monthCount: 286,
    kpis: [
      { label: '下書き件数', value: 48, unit: '件' },
      { label: '承認待ち件数', value: 32, unit: '件' },
      { label: '送信件数', value: 214, unit: '件' },
      { label: '成功件数', value: 197, unit: '件' },
      { label: '失敗件数', value: 17, unit: '件' },
      { label: '返信件数', value: 21, unit: '件' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 640000,
    outputTokens: 280000,
    costUsd: 12.1,
    avatar: '📮',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'email_sales',
    name: 'メール営業AI',
    role: 'メール営業AI',
    departmentId: 'sales',
    description: '営業メールの作成・返信分類・返信案の作成を担当。',
    responsibilities: ['件名作成', '本文作成', '企業ごとの文章調整', '承認申請', '返信内容の分類', '返信案の作成'],
    status: 'working',
    statusNote: '返信メール3件の返信案を作成中',
    progress: 40,
    todayCount: 27,
    monthCount: 342,
    kpis: [
      { label: '下書き件数', value: 36, unit: '件' },
      { label: 'メール送信件数', value: 306, unit: '件' },
      { label: '開封数', value: 141, unit: '件' },
      { label: '返信数', value: 28, unit: '件' },
      { label: '商談化数', value: 9, unit: '件' },
      { label: '配信停止数', value: 4, unit: '件' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 880000,
    outputTokens: 390000,
    costUsd: 16.6,
    avatar: '✉️',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'reception',
    name: '受付AI',
    role: '受付AI',
    departmentId: 'sales',
    description: '新規問い合わせの分類・一次返信案の作成・引き継ぎを担当。',
    responsibilities: ['問い合わせ分類', '緊急度判定', 'サービス別振り分け', '一次返信案の作成', '担当者への引き継ぎ'],
    status: 'checking',
    statusNote: '新着問い合わせ1件を分類中',
    progress: 30,
    todayCount: 4,
    monthCount: 52,
    kpis: [
      { label: '問い合わせ数', value: 52, unit: '件' },
      { label: '対応済み件数', value: 47, unit: '件' },
      { label: '未対応件数', value: 5, unit: '件' },
      { label: '平均初回対応時間', value: 18, unit: '分' },
      { label: '商談化件数', value: 11, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 210000,
    outputTokens: 74000,
    costUsd: 2.4,
    avatar: '💁',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'deal_mgr',
    name: '商談管理AI',
    role: '商談管理AI',
    departmentId: 'sales',
    description: '見込み客のステータス管理と商談の推進を担当。',
    responsibilities: ['ステータス管理', '商談要約', '次回アクション設定', '失注理由の記録', '案件化可能性の判定'],
    status: 'working',
    statusNote: '商談5件の次回アクションを更新中',
    progress: 55,
    todayCount: 8,
    monthCount: 96,
    kpis: [
      { label: '見込み客数', value: 143, unit: '件' },
      { label: '商談数', value: 21, unit: '件' },
      { label: '提案数', value: 12, unit: '件' },
      { label: '受注数', value: 5, unit: '件' },
      { label: '受注率', value: 24, unit: '%' },
      { label: '失注数', value: 6, unit: '件' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 420000,
    outputTokens: 130000,
    costUsd: 7.2,
    avatar: '🤝',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'tel',
    name: 'テレアポAI',
    role: 'テレアポAI',
    departmentId: 'sales',
    description: 'トークスクリプト作成と架電結果の管理(初期版は自動架電なし)。',
    responsibilities: ['架電対象リスト', 'トークスクリプト作成', '想定質問と回答', '架電結果の手動入力', '電話API連携IF(将来)'],
    status: 'idle',
    statusNote: '次の架電リスト待ち',
    progress: 0,
    todayCount: 0,
    monthCount: 34,
    kpis: [
      { label: '架電予定数', value: 60, unit: '件' },
      { label: '架電済み数', value: 34, unit: '件' },
      { label: '接続数', value: 19, unit: '件' },
      { label: '担当者接続数', value: 8, unit: '件' },
      { label: 'アポイント数', value: 3, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 96000,
    outputTokens: 41000,
    costUsd: 1.1,
    avatar: '📞',
    color: '#f59e0b',
  },
  {
    ...agentBase,
    id: 'sns',
    name: 'SNS運用AI',
    role: 'SNS運用AI',
    departmentId: 'marketing',
    description: 'SNS投稿の企画・文案作成・承認申請・分析を担当(初期版は実投稿なし)。',
    responsibilities: ['投稿企画', '投稿文作成', '投稿カレンダー', '画像制作依頼', '投稿承認申請', '数値分析', '改善提案'],
    status: 'working',
    statusNote: '来週分の投稿カレンダーを作成中 70%',
    progress: 70,
    todayCount: 5,
    monthCount: 63,
    kpis: [
      { label: '投稿予定数', value: 20, unit: '件' },
      { label: '下書き数', value: 8, unit: '件' },
      { label: '承認済み数', value: 6, unit: '件' },
      { label: '投稿済み数', value: 42, unit: '件' },
      { label: 'インプレッション', value: 128400, unit: '' },
      { label: 'クリック数', value: 1840, unit: '件' },
      { label: '問い合わせ数', value: 6, unit: '件' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 380000,
    outputTokens: 170000,
    costUsd: 7.6,
    avatar: '📣',
    color: '#ec4899',
  },
  {
    ...agentBase,
    id: 'seo',
    name: 'SEO・AIO AI',
    role: 'SEO・AIO AI',
    departmentId: 'marketing',
    description: 'キーワード調査・記事構成・AI検索最適化(AIO)を担当。',
    responsibilities: ['キーワード調査', '検索意図の分類', '競合ページ調査', '記事構成作成', 'FAQ作成', 'AIO情報設計', '既存記事の改善提案', '順位管理'],
    status: 'working',
    statusNote: '「採用サイト 制作」競合10ページを分析中',
    progress: 45,
    todayCount: 12,
    monthCount: 148,
    kpis: [
      { label: '調査キーワード数', value: 148, unit: '件' },
      { label: '記事構成数', value: 22, unit: '件' },
      { label: '完成記事数', value: 14, unit: '件' },
      { label: '検索流入数', value: 8620, unit: '件' },
      { label: '順位上昇数', value: 31, unit: '件' },
      { label: '問い合わせ数', value: 4, unit: '件' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 720000,
    outputTokens: 260000,
    costUsd: 12.8,
    avatar: '📈',
    color: '#ec4899',
  },
  {
    ...agentBase,
    id: 'director',
    name: 'ディレクターAI',
    role: 'ディレクターAI',
    departmentId: 'production',
    description: '制作案件全体の進行管理と要件定義を担当。',
    responsibilities: ['ヒアリング整理', '課題整理', 'ペルソナ設定', 'KPI設定', 'サイトマップ作成', 'ページ構成作成', 'スケジュール作成', 'タスク割り振り', '進行管理', '修正整理'],
    status: 'delegating',
    statusNote: 'ライターAIへ原稿作成を依頼中',
    progress: 68,
    todayCount: 9,
    monthCount: 118,
    kpis: [
      { label: '進行案件数', value: 3, unit: '件' },
      { label: '完了案件数', value: 7, unit: '件' },
      { label: '遅延案件数', value: 0, unit: '件' },
      { label: '要件確定数', value: 3, unit: '件' },
      { label: '修正回数', value: 14, unit: '回' },
    ],
    model: 'claude-fable-5',
    inputTokens: 980000,
    outputTokens: 310000,
    costUsd: 24.5,
    avatar: '🎬',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'writer',
    name: 'ライターAI',
    role: 'ライターAI',
    departmentId: 'production',
    description: 'コピーライティング・原稿作成を担当。',
    responsibilities: ['キャッチコピー', 'サービス紹介文', '会社紹介文', '採用コピー', 'CTA文', 'SEO記事', 'トーン調整'],
    status: 'working',
    statusNote: '田中製作所様 サービス紹介文を執筆中 55%',
    progress: 55,
    todayCount: 7,
    monthCount: 89,
    kpis: [
      { label: '作成原稿数', value: 89, unit: '本' },
      { label: '承認済み原稿数', value: 71, unit: '本' },
      { label: '修正回数', value: 23, unit: '回' },
      { label: '完了ページ数', value: 34, unit: 'ページ' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 560000,
    outputTokens: 420000,
    costUsd: 14.9,
    avatar: '✍️',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'designer',
    name: 'デザイナーAI',
    role: 'デザイナーAI',
    departmentId: 'production',
    description: 'ワイヤーフレーム・デザイン指示書・デザイン方針を担当。',
    responsibilities: ['ワイヤーフレーム作成', 'デザイン方針提案', '配色・フォント提案', 'UIパーツ設計', 'デザイン案作成', 'デザインシステム準拠確認'],
    status: 'working',
    statusNote: 'トップページワイヤー作成 65%',
    progress: 65,
    todayCount: 3,
    monthCount: 41,
    kpis: [
      { label: '制作中画面数', value: 5, unit: '画面' },
      { label: '完了画面数', value: 28, unit: '画面' },
      { label: '承認済み画面数', value: 24, unit: '画面' },
      { label: '修正回数', value: 11, unit: '回' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 480000,
    outputTokens: 210000,
    costUsd: 9.8,
    avatar: '🎨',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'coder',
    name: 'コーダーAI',
    role: 'コーダーAI',
    departmentId: 'production',
    description: 'HTML/CSS/React実装・レスポンシブ対応を担当。',
    responsibilities: ['HTML/CSS実装', 'React/Next.js実装', 'レスポンシブ対応', 'コンポーネント化', 'アニメーション', 'フォーム実装', 'CMS連携', 'アクセシビリティ'],
    status: 'working',
    statusNote: '佐藤工務店様 下層ページ実装中 42%',
    progress: 42,
    todayCount: 6,
    monthCount: 74,
    kpis: [
      { label: '実装ページ数', value: 74, unit: 'ページ' },
      { label: '完了コンポーネント数', value: 156, unit: '個' },
      { label: 'エラー数', value: 8, unit: '件' },
      { label: '修正件数', value: 19, unit: '件' },
      { label: 'ビルド成功率', value: 96, unit: '%' },
    ],
    model: 'claude-fable-5',
    inputTokens: 1240000,
    outputTokens: 680000,
    costUsd: 38.2,
    avatar: '💻',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'reviewer',
    name: 'レビュアーAI',
    role: 'レビュアーAI',
    departmentId: 'production',
    description: '品質チェック・コードレビュー・修正指示を担当。',
    responsibilities: ['誤字脱字チェック', '表示崩れチェック', 'リンク切れチェック', '要件整合性確認', 'レスポンシブ確認', 'アクセシビリティ確認', 'コードレビュー', '修正指示作成'],
    status: 'checking',
    statusNote: '3件の修正指示を作成中',
    progress: 60,
    todayCount: 11,
    monthCount: 132,
    kpis: [
      { label: 'レビュー件数', value: 132, unit: '件' },
      { label: '指摘件数', value: 87, unit: '件' },
      { label: '修正完了件数', value: 79, unit: '件' },
      { label: '未解決件数', value: 8, unit: '件' },
      { label: '再発率', value: 4, unit: '%' },
    ],
    model: 'claude-sonnet-5',
    inputTokens: 620000,
    outputTokens: 180000,
    costUsd: 10.3,
    avatar: '🔎',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'infra',
    name: 'インフラAI',
    role: 'インフラAI',
    departmentId: 'production',
    description: '公開環境・ビルド・ドメイン管理を担当(初期版は自動公開なし)。',
    responsibilities: ['公開環境設定', 'Vercel/Netlify公開準備', 'ドメイン設定管理', '環境変数管理', 'ビルド状況管理', '公開前チェック', '障害記録'],
    status: 'idle',
    statusNote: '公開待ち案件1件(承認待ち)',
    progress: 0,
    todayCount: 2,
    monthCount: 28,
    kpis: [
      { label: '公開待ち案件', value: 1, unit: '件' },
      { label: '公開済み案件', value: 7, unit: '件' },
      { label: 'ビルド成功数', value: 64, unit: '回' },
      { label: 'ビルド失敗数', value: 3, unit: '回' },
      { label: '障害件数', value: 0, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 140000,
    outputTokens: 52000,
    costUsd: 1.6,
    avatar: '🛠️',
    color: '#8b5cf6',
  },
  {
    ...agentBase,
    id: 'accountant',
    name: '経理AI',
    role: '経理AI',
    departmentId: 'admin',
    description: 'トークン利用量・原価・売上・粗利の管理を担当。',
    responsibilities: ['トークン利用量管理', 'API料金計算', 'ドル円換算', '案件別原価計算', '売上・粗利管理', '月次帳簿', 'CSV出力'],
    status: 'working',
    statusNote: '今月のAI利用料を集計中',
    progress: 82,
    todayCount: 3,
    monthCount: 45,
    kpis: [
      { label: '今月のAI利用料', value: 48210, unit: '円' },
      { label: '売上', value: 2350000, unit: '円' },
      { label: '粗利益', value: 1721000, unit: '円' },
      { label: '粗利益率', value: 73.2, unit: '%' },
      { label: '未請求金額', value: 680000, unit: '円' },
      { label: '入金待ち金額', value: 450000, unit: '円' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 180000,
    outputTokens: 60000,
    costUsd: 1.9,
    avatar: '🧮',
    color: '#10b981',
  },
  {
    ...agentBase,
    id: 'ops_admin',
    name: '管理AI',
    role: '管理AI',
    departmentId: 'admin',
    description: 'AI社員・権限・ルール・ログ・エラーの管理を担当。',
    responsibilities: ['AI社員一覧管理', '権限管理', '業務ルール管理', '契約・法務チェック', '個人情報管理', '操作ログ管理', 'エラー管理'],
    status: 'idle',
    statusNote: '監査ログを巡回中',
    progress: 0,
    todayCount: 1,
    monthCount: 22,
    kpis: [
      { label: '管理AI社員数', value: 18, unit: '名' },
      { label: '未解決エラー', value: 1, unit: '件' },
      { label: '監査ログ件数', value: 1204, unit: '件' },
    ],
    model: 'claude-haiku-4-5',
    inputTokens: 90000,
    outputTokens: 30000,
    costUsd: 0.9,
    avatar: '🗂️',
    color: '#10b981',
  },
].map((a) => ({ ...a, ...AGENT_PERSONAS[a.id] })) as Agent[];

// ---------- 営業リスト(32社) ----------
const companies: [string, string, string, string][] = [
  ['田中製作所', '製造業', '東京都', '30-50名'],
  ['佐藤工務店', '建設業', '神奈川県', '10-30名'],
  ['鈴木会計事務所', '士業', '東京都', '5-10名'],
  ['やまと歯科クリニック', '医療・介護', '大阪府', '10-30名'],
  ['グリーンフーズ', '飲食', '福岡県', '30-50名'],
  ['アーバン不動産', '不動産', '東京都', '50-100名'],
  ['ミナト精密工業', '製造業', '愛知県', '50-100名'],
  ['ひかり建設', '建設業', '大阪府', '30-50名'],
  ['さくら法律事務所', '士業', '東京都', '5-10名'],
  ['ケアホームつばき', '医療・介護', '神奈川県', '30-50名'],
  ['麺屋いちばん', '飲食', '東京都', '10-30名'],
  ['トライアングル不動産', '不動産', '愛知県', '10-30名'],
  ['ナカムラ金属', '製造業', '大阪府', '30-50名'],
  ['青空リフォーム', '建設業', '福岡県', '5-10名'],
  ['ワタナベ税理士法人', '士業', '神奈川県', '10-30名'],
  ['ふれあい整骨院グループ', '医療・介護', '東京都', '10-30名'],
  ['ベーカリーコムギ', '飲食', '神奈川県', '5-10名'],
  ['エステートパートナーズ', '不動産', '大阪府', '30-50名'],
  ['共和電子部品', '製造業', '福岡県', '50-100名'],
  ['マルコウ塗装', '建設業', '東京都', '5-10名'],
  ['いとう社労士事務所', '士業', '愛知県', '5-10名'],
  ['デイサービスひまわり', '医療・介護', '福岡県', '10-30名'],
  ['炭火焼肉 匠', '飲食', '大阪府', '10-30名'],
  ['ホームゲート', '不動産', '神奈川県', '10-30名'],
  ['オオタ樹脂加工', '製造業', '東京都', '10-30名'],
  ['タカハシ電設', '建設業', '愛知県', '10-30名'],
  ['ゆずりは行政書士事務所', '士業', '大阪府', '5-10名'],
  ['訪問看護ステーションあおい', '医療・介護', '愛知県', '10-30名'],
  ['カフェ・ルミエール', '飲食', '東京都', '5-10名'],
  ['サンライズ賃貸管理', '不動産', '福岡県', '30-50名'],
  ['フジイ機械設計', '製造業', '神奈川県', '10-30名'],
  ['ミライ空調サービス', '建設業', '大阪府', '30-50名'],
];

const leadStatuses = ['new', 'not_contacted', 'contacted', 'replied', 'scheduling', 'meeting_set', 'proposing', 'won', 'lost'] as const;

export const seedLeads: Lead[] = companies.map(([name, industry, region, size], i) => ({
  id: `lead_${i + 1}`,
  companyName: name,
  industry,
  region,
  employeeSize: size,
  url: `https://example.com/${i + 1}`,
  contactFormUrl: i % 3 === 0 ? null : `https://example.com/${i + 1}/contact`,
  email: i % 4 === 0 ? null : `info@example-${i + 1}.co.jp`,
  phone: `03-0000-${String(1000 + i)}`,
  contactPerson: i % 5 === 0 ? null : '代表者',
  reason: 'Webサイトが未更新(3年以上)で、スマホ非対応のため',
  hypothesis: '採用・集客の窓口としてWebサイトが機能していない可能性',
  proposal: i % 2 === 0 ? 'コーポレートサイトリニューアル + 採用ページ新設' : null,
  status: leadStatuses[i % leadStatuses.length],
  lastContactAt: i % 3 === 0 ? null : day(-(i % 14)),
  nextActionAt: i % 4 === 0 ? day((i % 7) + 1) : null,
  optedOut: i === 7,
  doNotContact: i === 19,
  memo: i === 7 ? '配信停止依頼あり(再送信禁止)' : '',
  campaignId: i < 20 ? 'camp_1' : 'camp_2',
  createdAt: day(-(30 - i)),
}));

export const seedCampaigns: Campaign[] = [
  {
    id: 'camp_1',
    name: '7月 製造・建設業向けリニューアル提案',
    channel: 'form',
    targetCondition: '製造業・建設業 / 東名阪福 / 5〜100名 / サイト3年以上未更新',
    status: 'active',
    totalLeads: 20,
    sent: 14,
    replied: 3,
    meetings: 2,
    createdAt: day(-12),
  },
  {
    id: 'camp_2',
    name: '採用サイト検討企業向けメールキャンペーン',
    channel: 'email',
    targetCondition: '採用ページ未設置 / 従業員10名以上 / 求人媒体掲載中',
    status: 'active',
    totalLeads: 12,
    sent: 8,
    replied: 2,
    meetings: 1,
    createdAt: day(-6),
  },
];

// ---------- 問い合わせ(5件) ----------
export const seedInquiries: Inquiry[] = [
  {
    id: 'inq_1',
    fromCompany: 'ハルカゼ商事',
    fromName: '営業部 部長',
    email: 'info@harukaze.example.jp',
    subject: 'コーポレートサイトのリニューアルについて',
    body: '現在のサイトが10年前のもので、リニューアルを検討しています。概算の費用感と納期を教えてください。',
    service: 'コーポレートサイト制作',
    urgency: 'high',
    status: 'new',
    draftReply: null,
    assigneeId: 'reception',
    receivedAt: iso(-45),
    firstResponseMinutes: null,
  },
  {
    id: 'inq_2',
    fromCompany: 'ニコニコ保育園',
    fromName: '園長',
    email: 'nikoniko@example.jp',
    subject: '採用サイトの制作費用について',
    body: '保育士の採用がうまくいっておらず、採用専用サイトを作りたいです。',
    service: '採用サイト制作',
    urgency: 'medium',
    status: 'triaged',
    draftReply: 'お問い合わせありがとうございます。採用サイト制作は35万円〜、納期は約6週間が目安です。まずは30分のオンラインヒアリングはいかがでしょうか。',
    assigneeId: 'reception',
    receivedAt: iso(-60 * 5),
    firstResponseMinutes: 22,
  },
  {
    id: 'inq_3',
    fromCompany: 'オリオン電機',
    fromName: '総務課',
    email: 'soumu@orion.example.jp',
    subject: '見積もり依頼(LP制作)',
    body: '新製品のランディングページを1枚お願いしたいです。8月末公開希望。',
    service: 'LP制作',
    urgency: 'high',
    status: 'replied',
    draftReply: null,
    assigneeId: 'reception',
    receivedAt: day(-2),
    firstResponseMinutes: 15,
  },
  {
    id: 'inq_4',
    fromCompany: 'クローバー美容室',
    fromName: 'オーナー',
    email: 'clover@example.jp',
    subject: 'SNS運用の代行はできますか',
    body: 'Instagramの運用を任せられるか知りたいです。',
    service: 'SNS運用代行',
    urgency: 'low',
    status: 'converted',
    draftReply: null,
    assigneeId: 'reception',
    receivedAt: day(-5),
    firstResponseMinutes: 31,
  },
  {
    id: 'inq_5',
    fromCompany: 'マツダ運送',
    fromName: '社長',
    email: 'matsuda@example.jp',
    subject: 'ドライバー採用ページの相談',
    body: 'ドライバー不足で困っています。採用に強いホームページにしたいです。',
    service: '採用サイト制作',
    urgency: 'medium',
    status: 'closed',
    draftReply: null,
    assigneeId: 'reception',
    receivedAt: day(-9),
    firstResponseMinutes: 12,
  },
];

// ---------- 商談(5件) ----------
export const seedDeals: Deal[] = [
  {
    id: 'deal_1',
    leadId: 'lead_1',
    companyName: '田中製作所',
    title: 'コーポレートサイトリニューアル',
    amountJpy: 850000,
    status: 'won',
    summary: '3年前のサイトを全面刷新。多言語対応は第2期に持ち越し。',
    nextAction: 'キックオフMTGの議事録共有',
    nextActionAt: day(1),
    lostReason: null,
    probability: 100,
    createdAt: day(-20),
  },
  {
    id: 'deal_2',
    leadId: 'lead_2',
    companyName: '佐藤工務店',
    title: '施工事例サイト + 採用ページ',
    amountJpy: 650000,
    status: 'won',
    summary: '施工事例を軸にした集客サイト。写真素材は顧客支給。',
    nextAction: 'デザイン案の顧客確認依頼',
    nextActionAt: day(2),
    lostReason: null,
    probability: 100,
    createdAt: day(-15),
  },
  {
    id: 'deal_3',
    leadId: null,
    companyName: 'クローバー美容室',
    title: 'SNS運用代行(月額)',
    amountJpy: 80000,
    status: 'proposing',
    summary: 'Instagram中心の月次運用。投稿12本/月 + 分析レポート。',
    nextAction: '提案書の送付(承認待ち)',
    nextActionAt: day(1),
    lostReason: null,
    probability: 70,
    createdAt: day(-4),
  },
  {
    id: 'deal_4',
    leadId: 'lead_7',
    companyName: 'ミナト精密工業',
    title: '多言語コーポレートサイト',
    amountJpy: 1200000,
    status: 'meeting_set',
    summary: '海外取引先向けに英語・中国語対応サイトを検討中。',
    nextAction: '来週火曜14:00 オンライン商談',
    nextActionAt: day(6),
    lostReason: null,
    probability: 45,
    createdAt: day(-8),
  },
  {
    id: 'deal_5',
    leadId: 'lead_11',
    companyName: '麺屋いちばん',
    title: '店舗サイト制作',
    amountJpy: 300000,
    status: 'lost',
    summary: '2店舗分の店舗サイト。予算感が合わず失注。',
    nextAction: '半年後に再アプローチ',
    nextActionAt: day(180),
    lostReason: '予算不足(競合の格安プランを選択)',
    probability: 0,
    createdAt: day(-18),
  },
];

// ---------- 制作案件(3件) ----------
export const seedProjects: Project[] = [
  {
    id: 'proj_1',
    name: '田中製作所 コーポレートサイトリニューアル',
    customerName: '田中製作所',
    serviceType: 'コーポレートサイト制作',
    orderAmountJpy: 850000,
    productionCostJpy: 120000,
    aiCostJpy: 18400,
    outsourcingCostJpy: 50000,
    directorId: 'director',
    memberIds: ['director', 'writer', 'designer', 'coder', 'reviewer', 'infra'],
    startDate: day(-14),
    deadline: day(30),
    status: 'active',
    phase: 'デザイン',
    progress: 55,
    requirements: '全12ページ。製品紹介・設備紹介・採用情報を強化。CMSで自社更新可能に。',
    purpose: '新規取引先からの信頼獲得と、採用応募数の増加',
    target: '取引先の調達担当者、機械系エンジニアの求職者',
    persona: '42歳・調達部課長。取引前に必ず会社HPを確認し、設備と品質体制を見る。',
    sitemap: ['トップ', '会社概要', '製品紹介', '設備紹介', '品質保証', '採用情報', 'ニュース', 'お問い合わせ'],
    pages: [
      { id: 'p1', name: 'トップ', status: 'design' },
      { id: 'p2', name: '会社概要', status: 'design' },
      { id: 'p3', name: '製品紹介', status: 'wireframe' },
      { id: 'p4', name: '設備紹介', status: 'writing' },
      { id: 'p5', name: '採用情報', status: 'writing' },
      { id: 'p6', name: 'お問い合わせ', status: 'planned' },
    ],
    assets: ['ロゴAIデータ', '工場内写真(撮影済み)', '社長メッセージ原稿'],
    revisions: [{ date: day(-3), content: 'トップのメインコピーをB案に変更' }],
    publishedUrl: null,
    createdAt: day(-20),
  },
  {
    id: 'proj_2',
    name: '佐藤工務店 施工事例サイト',
    customerName: '佐藤工務店',
    serviceType: 'コーポレートサイト制作',
    orderAmountJpy: 650000,
    productionCostJpy: 90000,
    aiCostJpy: 12100,
    outsourcingCostJpy: 0,
    directorId: 'director',
    memberIds: ['director', 'writer', 'designer', 'coder', 'reviewer'],
    startDate: day(-10),
    deadline: day(40),
    status: 'active',
    phase: 'コーディング',
    progress: 40,
    requirements: '施工事例をカテゴリ・エリアで絞り込めるギャラリー形式。全8ページ。',
    purpose: '「地域名+リフォーム」での検索流入と問い合わせ増加',
    target: '築20年以上の戸建てに住む50代夫婦',
    persona: '56歳・会社員。水回りのリフォームを検討中。施工事例と価格目安を重視。',
    sitemap: ['トップ', '施工事例', 'サービス', '会社案内', '採用', 'お問い合わせ'],
    pages: [
      { id: 'p1', name: 'トップ', status: 'coding' },
      { id: 'p2', name: '施工事例一覧', status: 'coding' },
      { id: 'p3', name: 'サービス', status: 'review' },
      { id: 'p4', name: '会社案内', status: 'done' },
      { id: 'p5', name: 'お問い合わせ', status: 'planned' },
    ],
    assets: ['施工写真120枚', 'お客様の声5件'],
    revisions: [],
    publishedUrl: null,
    createdAt: day(-15),
  },
  {
    id: 'proj_3',
    name: 'ニコニコ保育園 採用サイト',
    customerName: 'ニコニコ保育園',
    serviceType: '採用サイト制作',
    orderAmountJpy: 450000,
    productionCostJpy: 60000,
    aiCostJpy: 8200,
    outsourcingCostJpy: 30000,
    directorId: 'director',
    memberIds: ['director', 'writer', 'designer'],
    startDate: day(-4),
    deadline: day(50),
    status: 'active',
    phase: '要件整理',
    progress: 15,
    requirements: '保育士採用に特化。先輩インタビュー3本、1日の流れ、待遇FAQ。全6ページ。',
    purpose: '保育士の年間採用数を2名→5名へ',
    target: '20代の保育士(転職・新卒)',
    persona: '26歳・保育士4年目。人間関係と残業の少なさを重視して転職先を探している。',
    sitemap: ['トップ', '先輩インタビュー', '1日の流れ', '待遇・福利厚生', 'FAQ', '応募フォーム'],
    pages: [
      { id: 'p1', name: 'トップ', status: 'planned' },
      { id: 'p2', name: '先輩インタビュー', status: 'planned' },
      { id: 'p3', name: '待遇・福利厚生', status: 'planned' },
    ],
    assets: ['園内写真(撮影日程調整中)'],
    revisions: [],
    publishedUrl: null,
    createdAt: day(-5),
  },
];

// ---------- タスク(32件) ----------
const t = (
  id: number,
  title: string,
  assigneeId: string,
  status: Task['status'],
  progress: number,
  extra: Partial<Task> = {},
): Task => ({
  id: `task_${id}`,
  title,
  description: extra.description ?? title,
  assigneeId,
  requesterId: extra.requesterId ?? 'ceo',
  projectId: null,
  customerId: null,
  priority: 'medium',
  status,
  progress,
  plannedStart: null,
  deadline: day(3),
  startedAt: status === 'backlog' || status === 'queued' ? null : day(-1),
  completedAt: status === 'done' ? iso(-120) : null,
  needsApproval: false,
  approver: null,
  dependsOn: [],
  input: null,
  output: status === 'done' ? '完了成果物あり(詳細はログ参照)' : null,
  model: 'claude-sonnet-5',
  inputTokens: 12000 + id * 800,
  outputTokens: 4000 + id * 300,
  costUsd: 0.4 + id * 0.02,
  errorMessage: status === 'failed' ? 'フォームURLに到達できませんでした(404)' : null,
  createdAt: day(-2),
  ...extra,
});

export const seedTasks: Task[] = [
  t(1, '製造業・建設業 営業リスト300件作成', 'list', 'running', 51, { priority: 'high', description: '東名阪福の製造業・建設業から条件に合う300社を抽出し、重複を除外する。' }),
  t(2, 'フォーム営業文案 32件作成', 'form_sales', 'waiting_approval', 100, { needsApproval: true, approver: '社長', dependsOn: ['task_1'] }),
  t(3, '営業メール下書き 28件作成', 'email_sales', 'waiting_approval', 100, { needsApproval: true, approver: '社長' }),
  t(4, '返信メール3件の返信案作成', 'email_sales', 'running', 40),
  t(5, 'ハルカゼ商事 問い合わせ一次対応', 'reception', 'running', 30, { priority: 'urgent' }),
  t(6, '商談5件の次回アクション更新', 'deal_mgr', 'running', 55),
  t(7, 'ミナト精密工業 商談準備資料', 'deal_mgr', 'queued', 0, { deadline: day(5) }),
  t(8, '架電スクリプト(不動産業向け)作成', 'tel', 'backlog', 0),
  t(9, '来週分SNS投稿カレンダー作成', 'sns', 'running', 70),
  t(10, 'Instagram投稿文 5本下書き', 'sns', 'waiting_approval', 100, { needsApproval: true }),
  t(11, '「採用サイト 制作」競合調査', 'seo', 'running', 45),
  t(12, 'SEO記事「ホームページ リニューアル 費用」構成作成', 'seo', 'queued', 0, { dependsOn: ['task_11'] }),
  t(13, '田中製作所 要件定義書更新', 'director', 'done', 100, { projectId: 'proj_1' }),
  t(14, '田中製作所 トップページ原稿', 'writer', 'done', 100, { projectId: 'proj_1', requesterId: 'director' }),
  t(15, '田中製作所 サービス紹介文執筆', 'writer', 'running', 55, { projectId: 'proj_1', requesterId: 'director' }),
  t(16, '田中製作所 トップページワイヤー', 'designer', 'running', 65, { projectId: 'proj_1', requesterId: 'director', dependsOn: ['task_14'] }),
  t(17, '田中製作所 会社概要デザイン案', 'designer', 'queued', 0, { projectId: 'proj_1', requesterId: 'director' }),
  t(18, '佐藤工務店 トップページ実装', 'coder', 'running', 42, { projectId: 'proj_2', requesterId: 'director' }),
  t(19, '佐藤工務店 施工事例一覧 実装', 'coder', 'queued', 0, { projectId: 'proj_2', requesterId: 'director', dependsOn: ['task_18'] }),
  t(20, '佐藤工務店 サービスページレビュー', 'reviewer', 'running', 60, { projectId: 'proj_2', requesterId: 'director' }),
  t(21, '佐藤工務店 会社案内ページレビュー', 'reviewer', 'done', 100, { projectId: 'proj_2', requesterId: 'director' }),
  t(22, 'ニコニコ保育園 ヒアリング内容整理', 'director', 'running', 68, { projectId: 'proj_3' }),
  t(23, 'ニコニコ保育園 ペルソナ設定', 'director', 'queued', 0, { projectId: 'proj_3', dependsOn: ['task_22'] }),
  t(24, '田中製作所 公開前チェックリスト作成', 'infra', 'backlog', 0, { projectId: 'proj_1', needsApproval: true }),
  t(25, '6月分 月次帳簿作成', 'accountant', 'done', 100),
  t(26, '今月のAI利用料集計', 'accountant', 'running', 82),
  t(27, '商談候補日の作成(ミナト精密工業)', 'secretary', 'waiting_approval', 100, { needsApproval: true, approver: '社長' }),
  t(28, '未返信案件の洗い出し', 'secretary', 'done', 100),
  t(29, '操作ログの週次監査', 'ops_admin', 'done', 100),
  t(30, 'グリーンフーズ フォーム送信', 'form_sales', 'failed', 80, { errorMessage: 'フォームURLに到達できませんでした(404)' }),
  t(31, '営業週報の作成', 'ceo', 'queued', 0, { deadline: day(2) }),
  t(32, 'クローバー美容室 SNS運用提案書', 'sns', 'waiting_approval', 100, { needsApproval: true, priority: 'high' }),
];

// ---------- 承認待ち(6件) ----------
export const seedApprovals: Approval[] = [
  {
    id: 'apr_1',
    type: 'form_send',
    title: 'フォーム営業送信(32社)',
    requesterId: 'form_sales',
    target: '7月キャンペーン対象 32社',
    body: '【送信文サンプル】\n突然のご連絡失礼いたします。Web制作会社の「AI CREATIVE OFFICE」と申します。貴社サイトを拝見し、スマートフォン表示の改善で問い合わせ増加が見込めると感じ、ご連絡いたしました…(企業ごとに個別調整済み)',
    count: 32,
    estimatedCostJpy: 480,
    risks: ['送信先に既存顧客が含まれないことを確認済み', '営業禁止条件(官公庁・金融)該当なし'],
    hasDuplicates: false,
    hasOptedOutTargets: false,
    status: 'pending',
    taskId: 'task_2',
    createdAt: iso(-90),
    decidedAt: null,
  },
  {
    id: 'apr_2',
    type: 'email_send',
    title: '営業メール送信(28社)',
    requesterId: 'email_sales',
    target: '採用サイトキャンペーン対象 28社',
    body: '件名: 採用ページの改善で応募数を増やすご提案\n\n○○株式会社 ご担当者様\n\nはじめまして。AI CREATIVE OFFICEの…(企業ごとに件名・本文を個別調整済み)',
    count: 28,
    estimatedCostJpy: 420,
    risks: ['配信停止済み企業1社を送信対象から自動除外済み'],
    hasDuplicates: false,
    hasOptedOutTargets: true,
    status: 'pending',
    taskId: 'task_3',
    createdAt: iso(-150),
    decidedAt: null,
  },
  {
    id: 'apr_3',
    type: 'sns_post',
    title: 'Instagram投稿 5本',
    requesterId: 'sns',
    target: '@ai_creative_office(自社アカウント)',
    body: '①制作実績紹介(田中製作所様 ※掲載許諾済み)\n②Web制作の豆知識「スマホ対応の重要性」\n③スタッフ(AI社員)紹介\n④お客様の声\n⑤サービス紹介',
    count: 5,
    estimatedCostJpy: 120,
    risks: ['掲載許諾は取得済み', '個人情報の掲載なし'],
    hasDuplicates: false,
    hasOptedOutTargets: false,
    status: 'pending',
    taskId: 'task_10',
    createdAt: iso(-240),
    decidedAt: null,
  },
  {
    id: 'apr_4',
    type: 'customer_reply',
    title: 'ハルカゼ商事様への一次返信',
    requesterId: 'reception',
    target: 'info@harukaze.example.jp',
    body: 'ハルカゼ商事 様\n\nお問い合わせありがとうございます。コーポレートサイトのリニューアルは60万円〜、納期は約8週間が目安です。まずは現サイトの無料診断とオンラインヒアリング(30分)はいかがでしょうか。',
    count: 1,
    estimatedCostJpy: 15,
    risks: ['金額提示を含むため要確認'],
    hasDuplicates: false,
    hasOptedOutTargets: false,
    status: 'pending',
    taskId: 'task_5',
    createdAt: iso(-30),
    decidedAt: null,
  },
  {
    id: 'apr_5',
    type: 'quote_send',
    title: 'クローバー美容室様 SNS運用提案書送付',
    requesterId: 'sns',
    target: 'clover@example.jp',
    body: '月額8万円プラン: Instagram投稿12本/月、ストーリーズ8本、月次分析レポート、コメント返信案作成。初月はアカウント診断込み。',
    count: 1,
    estimatedCostJpy: 25,
    risks: ['見積金額を含むため要確認'],
    hasDuplicates: false,
    hasOptedOutTargets: false,
    status: 'pending',
    taskId: 'task_32',
    createdAt: iso(-300),
    decidedAt: null,
  },
  {
    id: 'apr_6',
    type: 'publish',
    title: '田中製作所様サイト ステージング公開',
    requesterId: 'infra',
    target: 'staging.tanaka-ss.example.jp',
    body: 'デザイン確認用のステージング環境を公開します。Basic認証あり。顧客確認用URLを発行します。',
    count: 1,
    estimatedCostJpy: 0,
    risks: ['Basic認証設定済み', '検索エンジンのインデックス防止設定済み'],
    hasDuplicates: false,
    hasOptedOutTargets: false,
    status: 'pending',
    taskId: 'task_24',
    createdAt: iso(-600),
    decidedAt: null,
  },
];

// ---------- 活動ログ(52件) ----------
const logDefs: [string, string, ActivityLog['status'], string | null, string | null][] = [
  ['ceo', '新規営業プロジェクト「7月 製造・建設業向け」を開始します。', 'info', 'task_1', null],
  ['list', '対象条件に一致する企業を128社取得しました。', 'success', 'task_1', null],
  ['list', '重複企業12社を除外しました。', 'info', 'task_1', null],
  ['form_sales', '32社分のフォーム送信文案を作成しました。承認待ちです。', 'warning', 'task_2', null],
  ['email_sales', '28社分の営業メール案を作成しました。承認待ちです。', 'warning', 'task_3', null],
  ['reception', '新しい問い合わせを1件受信しました(ハルカゼ商事様)。', 'info', 'task_5', null],
  ['reception', '緊急度「高」と判定し、一次返信案を作成しました。', 'success', 'task_5', null],
  ['secretary', '来週火曜日14時の商談候補を作成しました。', 'success', 'task_27', null],
  ['director', 'ニコニコ保育園様の要件整理を開始しました。', 'info', 'task_22', 'proj_3'],
  ['reviewer', 'トップページに4件の修正指示を作成しました。', 'warning', 'task_20', 'proj_2'],
  ['writer', '田中製作所様のトップページ原稿が完成しました。', 'success', 'task_14', 'proj_1'],
  ['designer', 'トップページワイヤーフレームの作成を開始しました。', 'info', 'task_16', 'proj_1'],
  ['coder', '佐藤工務店様トップページの実装を開始しました。', 'info', 'task_18', 'proj_2'],
  ['deal_mgr', 'ミナト精密工業様の商談を「商談予定」へ更新しました。', 'info', 'task_6', null],
  ['sns', '来週分の投稿カレンダーを作成中です(70%)。', 'info', 'task_9', null],
  ['seo', '「採用サイト 制作」の競合上位10ページの分析を開始しました。', 'info', 'task_11', null],
  ['accountant', '6月分の月次帳簿を作成しました。', 'success', 'task_25', null],
  ['form_sales', 'グリーンフーズ様のフォームURLに到達できませんでした(404)。', 'error', 'task_30', null],
  ['ops_admin', 'エラー1件を記録し、リスト作成AIへURL再確認を依頼しました。', 'info', null, null],
  ['ceo', '本日の優先タスクを再割り当てしました(緊急1件)。', 'info', null, null],
  ['secretary', '未返信案件3件を検出し、担当AIへリマインドしました。', 'warning', 'task_28', null],
  ['email_sales', 'ワタナベ税理士法人様から返信がありました。返信案を作成します。', 'success', 'task_4', null],
  ['deal_mgr', 'クローバー美容室様を「提案中」へ更新しました。', 'info', null, null],
  ['writer', 'サービス紹介文の執筆を開始しました(田中製作所様)。', 'info', 'task_15', 'proj_1'],
  ['reviewer', '会社案内ページのレビューが完了しました。指摘0件です。', 'success', 'task_21', 'proj_2'],
  ['infra', '田中製作所様のステージング公開チェックリストを作成しました。', 'info', 'task_24', 'proj_1'],
  ['ceo', '週次レポートの作成をキューに追加しました。', 'info', 'task_31', null],
  ['list', '営業対象外(官公庁関連)2社をリストから除外しました。', 'info', 'task_1', null],
  ['sns', 'Instagram投稿5本の下書きが完成しました。承認待ちです。', 'warning', 'task_10', null],
  ['seo', 'キーワード「ホームページ リニューアル 費用」を調査対象に追加しました。', 'info', 'task_12', null],
];

export const seedLogs: ActivityLog[] = [
  ...logDefs.map(([agentId, message, status, taskId, projectId], i) => ({
    id: `log_seed_${i}`,
    timestamp: iso(-(i * 17 + 5)),
    agentId,
    message,
    taskId,
    projectId,
    status,
  })),
  // 過去日のログ(履歴用)
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `log_hist_${i}`,
    timestamp: iso(-(60 * 10 + i * 55)),
    agentId: ['list', 'email_sales', 'writer', 'coder', 'reviewer', 'secretary', 'accountant'][i % 7],
    message: [
      '営業リストを25件追加しました。',
      '営業メールの開封を3件確認しました。',
      '原稿1本の修正が完了しました。',
      'コンポーネント3件の実装が完了しました。',
      'レビュー2件が完了しました。',
      '明日の予定リマインドを送信しました。',
      'AI利用料の日次集計が完了しました。',
    ][i % 7],
    taskId: null,
    projectId: null,
    status: 'info' as const,
  })),
];

// ---------- AI利用料金(直近レコード) ----------
export const seedUsage: AiUsageRecord[] = Array.from({ length: 40 }, (_, i) => {
  const agents = ['ceo', 'list', 'form_sales', 'email_sales', 'writer', 'designer', 'coder', 'reviewer', 'seo', 'sns'];
  const agentId = agents[i % agents.length];
  const models: Record<string, [string, string, number, number]> = {
    ceo: ['anthropic', 'claude-fable-5', 5, 25],
    coder: ['anthropic', 'claude-fable-5', 5, 25],
    list: ['anthropic', 'claude-haiku-4-5', 1, 5],
    form_sales: ['anthropic', 'claude-sonnet-5', 3, 15],
    email_sales: ['anthropic', 'claude-sonnet-5', 3, 15],
    writer: ['anthropic', 'claude-sonnet-5', 3, 15],
    designer: ['anthropic', 'claude-sonnet-5', 3, 15],
    reviewer: ['anthropic', 'claude-sonnet-5', 3, 15],
    seo: ['anthropic', 'claude-sonnet-5', 3, 15],
    sns: ['anthropic', 'claude-sonnet-5', 3, 15],
  };
  const [provider, model, inRate, outRate] = models[agentId];
  const inputTokens = 8000 + ((i * 3711) % 42000);
  const outputTokens = 2000 + ((i * 1913) % 18000);
  return {
    id: `usage_${i}`,
    provider,
    model,
    inputTokens,
    outputTokens,
    cachedTokens: Math.floor(inputTokens * 0.3),
    usdRateInput: inRate,
    usdRateOutput: outRate,
    costUsd: (inputTokens / 1e6) * inRate + (outputTokens / 1e6) * outRate,
    executedAt: iso(-(i * 47 + 10)),
    agentId,
    taskId: `task_${(i % 32) + 1}`,
    projectId: i % 3 === 0 ? `proj_${(i % 3) + 1}` : null,
  };
});

// ---------- 日別統計(直近14日) ----------
export const seedDailyStats: DailyStat[] = Array.from({ length: 14 }, (_, i) => {
  const offset = -(13 - i);
  const wave = Math.sin(i / 2.2) * 0.4 + 1;
  return {
    date: dateKey(offset),
    tasksCompleted: Math.round(9 * wave + i * 0.6),
    leadsAdded: Math.round(38 * wave),
    formsSent: Math.round(9 * wave),
    emailsSent: Math.round(12 * wave),
    inquiries: Math.round(1.6 * wave),
    meetings: Math.round(0.9 * wave),
    orders: i % 5 === 4 ? 1 : 0,
    costJpy: Math.round(2100 * wave + 600),
    revenueJpy: i % 5 === 4 ? 650000 : i % 7 === 3 ? 450000 : 0,
  };
});

// ---------- レポート ----------
export const seedReports: Report[] = [
  {
    id: 'rep_1',
    type: 'daily',
    periodLabel: `${dateKey(-1)} 日報`,
    createdAt: day(-1),
    body: [
      '# 日報',
      '## 実績',
      '- 実行タスク数: 21 / 完了: 14 / 失敗: 1',
      '- 営業リスト取得: 38件 / フォーム送信: 9件 / メール送信: 12件 / 返信: 2件',
      '- 問い合わせ: 2件 / 商談: 1件 / アポイント: 1件 / 受注: 0件',
      '- 制作進捗: 田中製作所様 デザイン55% / 佐藤工務店様 コーディング40%',
      '- 売上: ¥0 / AI利用料: ¥2,840 / 粗利益: -¥2,840',
      '## 課題',
      '- フォームURL 404が1件発生(グリーンフーズ様)',
      '## 改善案',
      '- リスト作成時にフォームURLの死活確認を追加する',
      '## 翌日の優先事項',
      '- ハルカゼ商事様への一次返信(承認後即送信)',
      '- フォーム営業32件の承認取得',
    ].join('\n'),
  },
  {
    id: 'rep_2',
    type: 'weekly',
    periodLabel: '先週の週報',
    createdAt: day(-3),
    body: [
      '# 週報',
      '## サマリー',
      '- 完了タスク: 68件 / 営業リスト: 214件 / メール送信: 64件 / 返信: 9件',
      '- 商談: 4件 / 受注: 1件(佐藤工務店様 ¥650,000)',
      '- AI利用料: ¥11,920 / 粗利益率: 73.2%',
      '## 所感',
      '- フォーム営業の返信率が2.1%→3.4%に改善(文面Bパターンが有効)',
      '## 来週の優先事項',
      '- ミナト精密工業様 商談(火曜14:00)',
      '- 田中製作所様 デザイン顧客確認',
    ].join('\n'),
  },
];

// ---------- エラー ----------
export const seedErrors: ErrorRecord[] = [
  {
    id: 'err_1',
    timestamp: iso(-320),
    agentId: 'form_sales',
    taskId: 'task_30',
    message: 'フォームURL 404 Not Found',
    detail: 'https://example.com/5/contact への送信テストが404で失敗。リストのURL再確認が必要。',
    resolved: false,
  },
  {
    id: 'err_2',
    timestamp: day(-2),
    agentId: 'coder',
    taskId: 'task_18',
    message: 'ビルドエラー(型不一致)',
    detail: 'GalleryProps の型不一致でビルド失敗。修正済み・再ビルド成功。',
    resolved: true,
  },
];

// ---------- SNS投稿 ----------
export const seedSnsPosts: SnsPost[] = [
  { id: 'sns_1', platform: 'Instagram', title: '制作実績紹介(田中製作所様)', body: '製造業のコーポレートサイトを全面リニューアル…', scheduledAt: day(2), status: 'waiting_approval', impressions: 0, clicks: 0 },
  { id: 'sns_2', platform: 'Instagram', title: 'Web制作の豆知識', body: 'スマホ対応していないサイト、実は7割の訪問者を逃しています…', scheduledAt: day(3), status: 'waiting_approval', impressions: 0, clicks: 0 },
  { id: 'sns_3', platform: 'X', title: 'AI社員紹介 #1', body: '弊社のリスト作成AIは1日300社を調査します…', scheduledAt: day(4), status: 'draft', impressions: 0, clicks: 0 },
  { id: 'sns_4', platform: 'LinkedIn', title: '採用サイトの作り方', body: '応募数を増やす採用サイトの3つの共通点…', scheduledAt: day(5), status: 'draft', impressions: 0, clicks: 0 },
  { id: 'sns_5', platform: 'Instagram', title: 'お客様の声(佐藤工務店様)', body: '「問い合わせが2倍になりました」…', scheduledAt: day(-3), status: 'posted', impressions: 4820, clicks: 96 },
  { id: 'sns_6', platform: 'X', title: 'ホームページ無料診断のご案内', body: '現サイトの改善ポイントを無料で診断します…', scheduledAt: day(-5), status: 'posted', impressions: 2140, clicks: 41 },
];

// ---------- SEOキーワード ----------
export const seedSeoKeywords: SeoKeyword[] = [
  { id: 'kw_1', keyword: 'ホームページ制作 相場', intent: '比較検討', volume: 5400, difficulty: 62, rank: 18, articleStatus: 'published' },
  { id: 'kw_2', keyword: '採用サイト 制作', intent: '比較検討', volume: 2900, difficulty: 58, rank: 24, articleStatus: 'writing' },
  { id: 'kw_3', keyword: 'ホームページ リニューアル 費用', intent: '比較検討', volume: 1900, difficulty: 45, rank: null, articleStatus: 'outline' },
  { id: 'kw_4', keyword: '中小企業 ホームページ 必要性', intent: '情報収集', volume: 880, difficulty: 30, rank: 8, articleStatus: 'published' },
  { id: 'kw_5', keyword: '工務店 ホームページ 事例', intent: '情報収集', volume: 720, difficulty: 28, rank: 5, articleStatus: 'published' },
  { id: 'kw_6', keyword: 'AIO対策 とは', intent: '情報収集', volume: 1600, difficulty: 35, rank: 12, articleStatus: 'published' },
];

// ---------- 外部連携 ----------
export const seedIntegrations: Integration[] = [
  { id: 'int_claude', name: 'Claude API', category: 'AIプロバイダー', description: 'AI社員の思考エンジン(メイン)', status: 'not_connected', requiredEnv: ['ANTHROPIC_API_KEY'] },
  { id: 'int_openai', name: 'OpenAI API', category: 'AIプロバイダー', description: 'AI社員の思考エンジン(サブ)', status: 'not_connected', requiredEnv: ['OPENAI_API_KEY'] },
  { id: 'int_gemini', name: 'Google Gemini', category: 'AIプロバイダー', description: 'AI社員の思考エンジン(サブ)', status: 'not_connected', requiredEnv: ['GOOGLE_AI_API_KEY'] },
  { id: 'int_gmail', name: 'Gmail', category: 'メール', description: '営業メール・返信の送受信', status: 'not_connected', requiredEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'] },
  { id: 'int_gcal', name: 'Google Calendar', category: 'スケジュール', description: '日程調整・会議予定の管理', status: 'not_connected', requiredEnv: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'] },
  { id: 'int_supabase', name: 'Supabase', category: 'データベース', description: 'データ永続化・認証・Realtime', status: 'not_connected', requiredEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY'] },
  { id: 'int_search', name: 'Web検索API', category: 'リサーチ', description: '営業リスト作成・競合調査', status: 'not_connected', requiredEnv: ['SEARCH_API_KEY'] },
  { id: 'int_sns', name: 'SNS API (X/Instagram/etc)', category: 'SNS', description: 'SNS投稿の自動化', status: 'not_connected', requiredEnv: ['SNS_API_KEYS'] },
  { id: 'int_vercel', name: 'Vercel', category: 'ホスティング', description: '制作サイトの公開', status: 'not_connected', requiredEnv: ['VERCEL_TOKEN'] },
  { id: 'int_netlify', name: 'Netlify', category: 'ホスティング', description: '制作サイトの公開(サブ)', status: 'not_connected', requiredEnv: ['NETLIFY_AUTH_TOKEN'] },
  { id: 'int_figma', name: 'Figma', category: 'デザイン', description: 'デザインデータ連携', status: 'not_connected', requiredEnv: ['FIGMA_ACCESS_TOKEN'] },
  { id: 'int_crm', name: 'CRM (HubSpot等)', category: 'CRM', description: '顧客・商談データ連携', status: 'not_connected', requiredEnv: ['CRM_API_KEY'] },
  { id: 'int_tel', name: '電話API (Twilio等)', category: '電話', description: '将来のテレアポ連携用', status: 'disabled', requiredEnv: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN'] },
];

// ---------- チャット初期メッセージ ----------
export const seedChat: ChatMessage[] = [
  {
    id: 'chat_1',
    role: 'ceo_ai',
    content:
      'おはようございます、社長。CEO AIです。現在、進行中の案件は3件、承認待ちが6件あります。承認センターのご確認をお願いします。新しいご指示があればお気軽にどうぞ。',
    timestamp: iso(-60),
  },
];
